"""empty message

Revision ID: 1532247780bc
Revises: 76fa3ed0b3f3
Create Date: 2022-07-28 10:15:58.613545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1532247780bc'
down_revision = '76fa3ed0b3f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_code', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_code')
    # ### end Alembic commands ###
