"""tag 

Revision ID: 5de6cd56aec0
Revises: a31e40958dc6
Create Date: 2022-08-02 14:49:03.794042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de6cd56aec0'
down_revision = 'a31e40958dc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
