"""Add User, Category, Tag, Post models

Revision ID: 76fa3ed0b3f3
Revises: 8d59b57e5623
Create Date: 2022-07-26 11:08:50.764378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fa3ed0b3f3'
down_revision = '8d59b57e5623'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
