"""Add User, Category, Tag, Post models

Revision ID: c2b6030858f0
Revises: 1532247780bc
Create Date: 2022-07-28 10:18:20.078682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b6030858f0'
down_revision = '1532247780bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
